# Generated by Django 3.1.5 on 2022-01-23 12:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=50)),
                ('project_id', models.IntegerField()),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('H', 'On Hold'), ('P', 'In Progress'), ('F', 'Finished'), ('C', 'Confirmed')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('employeeID', models.IntegerField()),
                ('designation', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=255)),
                ('department', models.CharField(choices=[('E', 'Electrical'), ('M', 'Mechanical'), ('S', 'Software'), ('A', 'Admin'), ('O', 'Other')], default='O', max_length=15)),
                ('CurrentlyWorking', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('M', 'Manager'), ('T', 'Team Leader'), ('E', 'Engineer'), ('A', 'Administrator')], max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('task_description', models.CharField(blank=True, max_length=1000)),
                ('task_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projects')),
            ],
        ),
        migrations.CreateModel(
            name='assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_start_date', models.DateField(default=datetime.date.today)),
                ('assignment_end_date', models.DateField(null=True)),
                ('assignment_status', models.CharField(choices=[('H', 'On Hold'), ('P', 'In Progress'), ('F', 'Finished'), ('C', 'Confirmed')], max_length=15)),
                ('asignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.users')),
                ('assigned_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.projects')),
                ('assigned_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.tasks')),
            ],
        ),
    ]
