# Generated by Django 3.1.5 on 2022-01-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='department',
            field=models.CharField(choices=[('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Software', 'Software'), ('Admin', 'Admin'), ('Other', 'Other')], default='O', max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Team-Leader', 'Team Leader'), ('Engineer', 'Engineer'), ('Administrator', 'Administrator'), ('Other', 'Other')], max_length=25, null=True),
        ),
    ]
