# Generated by Django 3.1.5 on 2022-02-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='time_req',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='work_done',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assignments',
            name='work_done_temp',
            field=models.FloatField(default=0),
        ),
    ]
